export const DERIVATIVE_PLATFORM_ORDER: string[];
export const SCIENCE_CHANNELS: string[];
export const DERIVATIVE_PROMPT_VERSION: string;
export function isDerivativesEnabled(value?: string): boolean;
export function derivativeLanguages(platform: string): string[];
export function isScienceChannel(platform: string): boolean;
export function shouldSkipSciencePlatform(platform: string, parentText?: string): boolean;
export function selectPlatformSpec(specs: Array<any>, platform: string, format: string): Record<string, any>;
export function buildKnowledgeDirectoryForPrompt(directory: Array<any>): Array<{ id: string; title: string; author: string; domain: string; subdomain: string }>;
export function isMetaphysicalTopic(text?: string): boolean;
export function getMissingMarkers(text?: string): string[];
export function ensureScienceMarker(content: string, hasAllowedSource: boolean): string;
export function carryMissingMarkers(parentText: string, derivativeText: string): string;
export function checkPlainText(text?: string): string[];
export function scanSensitiveRules(text: string, rules?: Array<any>, languageVersion?: string): Array<{ term: string; category: string; source_urls: string[]; status: string; block_available: boolean }>;
export function contentMetrics(content: string | object, spec?: Record<string, any>): { character_count: number; slide_count: number; hashtag_count: number; warnings: string[] };
export function validateDerivativePayload(platform: string, payload?: Record<string, any>): boolean;
export function formatDerivativeContent(platform: string, languageVersion: string, payload?: Record<string, any>): string;
export function deriveChecks(input: { parentText: string; content: string; platform: string; languageVersion: string; rules?: Array<any>; spec?: Record<string, any>; existingGuardrailPassed?: boolean; humanConfirmed?: boolean }): Record<string, any>;
export function stableParentId(brandId: string, platform: string, content: string): string;
